AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a service on AWS Fargate, hosted in a public subnet, and accessible via a public load balancer.
Parameters:
  # Provide name of networking stack that was created in the previous step 
  StackName:
    Type: String
    Default: FargateNetworkingStack
    Description: The name of the networking Fargate stack that was created in last step. Exported Outputs are used from this stack.
  # Provide service name, by default this is provided as blockchain
  ServiceName:
    Type: String
    Default: blockchain
    Description: Name for the blockchain service
  # Provide image url of the blockchain container. Since we have it store in ECR, and this is not public. 
  # Therefore, please docker build this code here https://github.com/backdoorcodr/blockchain-on-kubernetes
  # and publish it on relevant containers repository. 
  ImageUrl:
    Type: String
    Default: 399827803559.dkr.ecr.eu-west-1.amazonaws.com/blockchain:3000
    Description: Blockchain container image url of the blockchain container. Read comment above. 
  # Update exposed container port. 
  ContainerPort:
    Type: Number
    Default: 3000
    Description: Exposed container port.
  # Container resources configuration
  ContainerCpu:
    Type: Number
    Default: 256
    Description: Amount of CPU reserved for container.
  ContainerMemory:
    Type: Number
    Default: 512
    Description:Amount of RAM reserved for container.
  Path:
    Type: String
    Default: "*"
    Description: A path on the public load balancer that this service
                 should be connected to. 
  Priority:
    Type: Number
    Default: 1
    Description: Priority of the routing rule. Relevant when we have multiple services running. 
  DesiredCount:
    Type: Number
    Default: 2
    Description: Fixed number of running tasks
  Role:
    Type: String
    Default: ""
    Description: (Optional) IAM role to access other AWS resources for e.g. S3, DynamoDB etc



